"""Component identifiers used by the Dash portal."""

SOURCE_PATHS = "astrometry-source-paths"
DISCOVER_FILES = "astrometry-discover-files"
RECURSIVE_SEARCH = "astrometry-recursive-search"
DISCOVERY_STATUS = "astrometry-discovery-status"
FILE_SELECT = "astrometry-file-select"
CHANNEL = "astrometry-channel"
LOAD_IMAGE = "astrometry-load-image"
DETECTOR = "astrometry-detector"
STATUS = "astrometry-load-status"
IMAGE_GRAPH = "astrometry-image-graph"
METADATA_BODY = "astrometry-metadata-body"
LOG_WINDOW = "astrometry-log-window"
LOG_POLL_INTERVAL = "astrometry-log-poll-interval"
LOG_AUTOSCROLL_DUMMY = "astrometry-log-autoscroll-dummy"
BTN_EXIT = "astrometry-exit"
