"""Component identifiers used by the Dash portal."""

SOURCE_PATHS = "astrometry-source-paths"
DISCOVER_FILES = "astrometry-discover-files"
RECURSIVE_SEARCH = "astrometry-recursive-search"
DISCOVERY_STATUS = "astrometry-discovery-status"
FILE_SELECT = "astrometry-file-select"
CHANNEL = "astrometry-channel"
LOAD_IMAGE = "astrometry-load-image"
DETECTOR = "astrometry-detector"
STATUS = "astrometry-load-status"
IMAGE_GRAPH = "astrometry-image-graph"
METADATA_BODY = "astrometry-metadata-body"
LOG_WINDOW = "astrometry-log-window"
LOG_POLL_INTERVAL = "astrometry-log-poll-interval"
LOG_AUTOSCROLL_DUMMY = "astrometry-log-autoscroll-dummy"
BTN_EXIT = "astrometry-exit"
DETECTION_THRESHOLD = "astrometry-detection-threshold"
DETECTION_FWHM = "astrometry-detection-fwhm"
DETECTION_MIN_PIXELS = "astrometry-detection-min-pixels"
DETECT_SOURCES = "astrometry-detect-sources"
DETECTION_STATUS = "astrometry-detection-status"
SHOW_DETECTION_MASKS = "astrometry-show-detection-masks"
